%% Import data from text file.
% Script for importing data from the following text file:
%
%    /Users/mikhail/Desktop/SOURCE_DATA/cabspottingdata/new_abboip.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2014/05/27 14:20:06

%% Initialize variables.

% clearvars X T

% load good_idx
files = dir('GPS/data/new_*');

% for i = 1:length(good_idx)
%   filename = files(good_idx(i)).name;

for i = 1:length(files)
  filename = files(i).name;
  
  %% Format string for each line of text:
  %   column1: double (%f)
  %	column2: double (%f)
  %   column3: double (%f)
  %	column4: double (%f)
  % For more information, see the TEXTSCAN documentation.
  formatSpec = '%8f%11f%2f%f%[^\n\r]';
  
  %% Open the text file.
  fileID = fopen(filename,'r');
  
  %% Read columns of data according to format string.
  % This call is based on the structure of the file used to generate this
  % code. If an error occurs for a different file, try regenerating the code
  % from the Import Tool.
  dataArray = textscan(fileID, formatSpec, 'Delimiter', '', 'WhiteSpace', '', 'EmptyValue' ,NaN, 'ReturnOnError', false);
  
  %% Close the text file.
  fclose(fileID);
  
  %% Post processing for unimportable data.
  % No unimportable data rules were applied during the import, so no post
  % processing code is included. To generate code which works for
  % unimportable data, select unimportable cells in a file and regenerate the
  % script.
  
  %% Allocate imported array to column variable names
  X_all{i}(:,1) = dataArray{:,1};
  X_all{i}(:,2) = dataArray{:,2};
  X_all{i}(:,3) = dataArray{:,3};
  T_all{i} = dataArray{:,4};
  
  X_all{i} = flipud(X_all{i});
  T_all{i} = flipud(T_all{i});
  
  min_X1{i} = min(X_all{i}(:,1));
  min_X2{i} = min(X_all{i}(:,2));
  X_all{i}(:,1) = X_all{i}(:,1)-min_X1{i};
  X_all{i}(:,2) = X_all{i}(:,2)-min_X2{i};
  
  T_all{i} = T_all{i}-min(T_all{i})+1;
  
  T_all{i} = T_all{i}(T_all{i}<=60*60*12);
  X_all{i} = X_all{i}(1:size(T_all{i},1),:);
  
  delta_T{i} = filter([1,-1],1,T_all{i});
  
  %% Clear temporary variables
  clearvars filename formatSpec fileID dataArray ans;
  fprintf('.')
  
end

clearvars i
fprintf('\n')

%%
% figure(401)
% for i = 1:16
%   subplot(4,4,i)
%   hold on
%   plot(X{i}(:,1),X{i}(:,2))
% end
%
% figure(402)
% for i = 1:16
%   subplot(4,4,i)
%   hold on
%   plot(T{i},X{i}(:,1),'bx')
%   plot(T{i},X{i}(:,2),'gx')
% end
